
  #define GlobalConstants_Sim_RoomBaseCamera 0
#define GlobalConstants_Renderer_UseDebugCamera 0
#define GlobalConstants_Renderer_Camera_DebugCameraDistance 15.00f
#define GlobalConstants_Renderer_ShowLightning_SampleSource 0
#define GlobalConstants_GroundChunk_ReGenGroundChunkOnReload 0
#define GlobalConstants_Renderer_WeirdDrawBufferSize 0
#define GlobalConstants_GroundChunk_ShowGroundChunkOutlines 0
#define GlobalConstants_Sim_FamiliarFollowsHero 0
#define GlobalConstants_Particle_Demo 0
#define GlobalConstants_Particle_Grid 0
#define GlobalConstants_Renderer_Show_Space_Outline 1
#define GlobalConstants_Renderer_Camera 20.0f